import fs from "fs";
const h = fs.readFileSync("index.html", "utf8");
const m = h.match(/const CLUES = (\{[\s\S]*?\});\nconst POOLS/);
if (!m) { console.log("no clues"); process.exit(1); }
const CLUES = JSON.parse(m[1]);
const have = new Set(Object.keys(CLUES));

const EXTRA = {
  LION:"A big cat with a mane", WOLF:"A wild dog that howls", DEER:"A woodland animal with antlers",
  LAMB:"A young sheep", GOAT:"A farm animal with horns", COW:"It gives milk", PIG:"A farm animal that oinks",
  HEN:"A female chicken", OWL:"A bird that hunts at night", ANT:"A tiny insect that lives in a colony",
  BEE:"It makes honey", FOX:"A clever red wild dog", CUB:"A young bear or lion", PUP:"A young dog",
  KIT:"A young cat", DEN:"An animal's home", NEST:"Where a bird lays eggs", LEAF:"The green part of a plant",
  TWIG:"A small branch", BARK:"The skin of a tree", MUD:"Wet dirt", SAND:"Tiny grains on a beach",
  ROCK:"A hard stone", HILL:"A small mountain", LAKE:"A body of water surrounded by land",
  POND:"A small lake", SEA:"The salty water beyond the shore", SKY:"The blue above you",
  FOG:"A cloud sitting on the ground", WIND:"Moving air", ICE:"Frozen water", DAY:"The time of sunlight",
  NIGHT:"The time of darkness", LOCK:"It needs a key", GATE:"A door in a fence", PATH:"A narrow way to walk",
  ROAD:"Cars drive on this", SIGN:"A board that gives a message", SHOP:"A place that sells things",
  BANK:"Where money is kept", PARK:"A green public space", ZOO:"A place to see wild animals",
  FARM:"Where crops and animals are raised", BARN:"A farm building for hay", ROOF:"The top of a house",
  WALL:"The side of a room", LAMP:"A light you switch on", DESK:"A table for writing", SOFA:"A long soft seat",
  RUG:"A floor covering", MUG:"A cup with a handle", PAN:"It is used for frying", POT:"It is used for boiling",
  BOWL:"A deep round dish", SPOON:"You eat soup with this", FORK:"It has prongs", KNIFE:"It cuts food",
  PLATE:"Food is served on this", JUICE:"A drink squeezed from fruit", HONEY:"Sweet food made by bees",
  NUT:"A hard-shelled seed", PEA:"A small green vegetable", BEAN:"A seed cooked as a vegetable",
  SOUP:"A liquid meal", STEW:"A thick cooked meal", COCOA:"A hot chocolate drink", SHOE:"Worn on the foot",
  SOCK:"Worn inside a shoe", CAP:"A soft hat with a brim", BELT:"It holds up trousers", BIN:"A container for rubbish",
  CAN:"A metal food container", JAR:"A glass container", TUB:"A wide container, or a bath",
  MOON:"It shines at night", KING:"A male ruler", QUEEN:"A female ruler", APPLE:"A common round fruit",
  BREAD:"A loaf made from flour", WATER:"You drink it to live", HOUSE:"A building you live in",
  GREEN:"The color of grass", HORSE:"An animal you can ride", MOUSE:"A small animal cats chase",
  PLANT:"A living thing with leaves", CHAIR:"A seat with a back", TABLE:"You eat at this",
  SMILE:"A happy look on a face", HAPPY:"Feeling joy", LIGHT:"The opposite of dark",
  PHONE:"You call people with this", PAPER:"You write on this", CANDY:"A sweet treat",
  SHIP:"A large boat", BOAT:"It floats on water", TRAIN:"It runs on rails", PLANE:"It flies in the sky",
  BIKE:"A two-wheeled ride", KITE:"It flies on a string", DRUM:"You beat this instrument",
  BELL:"It rings", FLAG:"A cloth of a country", CROWN:"Worn by a king or queen",
  RING:"Jewelry for a finger", COIN:"A piece of money", NOTE:"A short written message",
  CARD:"A stiff piece of paper, or a greeting", GIFT:"Something given", CAVE:"A hollow in a rock",
  WAVE:"A moving ridge of water", BEACH:"Sand beside the sea", SHELL:"A hard cover from the sea",
  CRAB:"A sideways-walking sea animal", WHALE:"The largest sea animal", SHARK:"A fish with sharp teeth",
  SNAKE:"A long animal with no legs", TIGER:"A big striped cat", ZEBRA:"A horse-like animal with stripes",
  CAMEL:"A desert animal with a hump", SHEEP:"It gives wool", WOOL:"Soft hair from a sheep",
  CORN:"A yellow grain on a cob", RICE:"A grain cooked in water", SALT:"It makes food taste sharper",
  SUGAR:"It makes food sweet", LEMON:"A sour yellow fruit", GRAPE:"A small fruit that grows in bunches",
  PEACH:"A soft fruit with a stone", MELON:"A large sweet fruit", BERRY:"A small juicy fruit",
  CLOUD:"A white shape in the sky", STORM:"Wild wind and rain",
  BLANKET:"A warm cover for a bed", PILLOW:"You rest your head on this", MATTRESS:"The soft part of a bed",
  CURTAIN:"Cloth hung at a window", CARPET:"A soft covering for a whole floor", CUPBOARD:"A cabinet for dishes or food",
  DRAWER:"A box that slides out of a desk", CLOSET:"A small room for clothes", ATTIC:"The space under the roof",
  CELLAR:"A room under the house", PORCH:"A covered entrance", FOUNTAIN:"Water that sprays upward",
  STATUE:"A carved figure", TORCH:"A flaming stick used as a light", MATCH:"A small stick that strikes a flame",
  FLAME:"The bright part of a fire", SMOKE:"The grey cloud from a fire", ASHES:"What a fire leaves behind",
  EMBER:"A glowing bit of burnt wood", SPARK:"A tiny flash from a fire", FLASH:"A sudden burst of light",
  GLEAM:"A soft shine", GLOW:"A steady soft light", SHADOW:"A dark shape cast by light",
  SHADE:"Shelter from the sun", TWILIGHT:"The dim light after sunset", DAWN:"The first light of day",
  DUSK:"The last light of day", BREEZE:"A gentle wind", GUST:"A sudden rush of wind",
  SQUALL:"A short violent wind", DRIZZLE:"Very light rain", SHOWER:"A brief fall of rain",
  PUDDLE:"A small pool after rain", STREAM:"A small flowing river", CREEK:"A narrow stream",
  BROOK:"A small fresh stream", RAPIDS:"Fast rocky water", WATERFALL:"Water falling over a cliff",
  MEADOW:"A grassy field", PASTURE:"Land where animals graze", ORCHARD:"A field of fruit trees",
  VINEYARD:"Where grapes are grown", HARVEST:"The gathering of crops", GRANARY:"A store for grain",
  SILO:"A tall store for grain", BARNYARD:"The yard around a barn", HAYLOFT:"The upper part of a barn",
  STABLE:"Where horses are kept", PADDOCK:"A fenced field for horses", SADDLE:"The seat on a horse",
  BRIDLE:"Straps on a horse's head", REINS:"What you hold to guide a horse", HORSESHOE:"A metal shoe for a horse",
  WAGON:"A cart pulled by animals", CARRIAGE:"A horse-drawn passenger coach", BUGGY:"A light horse carriage",
  COACH:"A large enclosed carriage", RAILWAY:"The track a train runs on", DEPOT:"A station for trains or buses",
  PLATFORM:"Where you wait for a train", CONDUCTOR:"The person in charge of a train", PORTER:"A person who carries bags",
  LUGGAGE:"Bags taken on a journey", SUITCASE:"A traveling bag with a handle", PASSPORT:"A book that lets you cross borders",
  VISA:"Permission stamped for travel", CUSTOMS:"The checkpoint for goods at a border", BORDER:"The line between countries",
  VILLAGE:"A small country settlement", HAMLET:"A tiny village", COTTAGE:"A small country house",
  MANOR:"A large country house", ESTATE:"A large piece of owned land", GROUNDS:"The land around a house",
  HEDGE:"A living fence of bushes", MAZE:"A puzzle of paths", TERRACE:"A raised flat outdoor space",
  BALCONY:"A platform outside an upper window", STAIRCASE:"A flight of steps", CORRIDOR:"A long indoor passage",
  CHAMBER:"A formal room", PANTRY:"A store for food", LARDER:"A cool room for food", SCULLERY:"A room for washing dishes",
  HEARTH:"The floor of a fireplace", MANTEL:"The shelf above a fireplace", CHIMNEY:"The flue that carries smoke up",
  BELFRY:"The tower where bells hang", STEEPLE:"A tall church spire", WEATHERVANE:"It shows which way the wind blows",
  FLAGPOLE:"The staff a flag flies from", BANNER:"A long flag", CREST:"A family emblem", EMBLEM:"A symbol of a group",
  BADGE:"A small mark of membership", MEDAL:"A prize worn on a ribbon", RIBBON:"A narrow strip of cloth",
  TROPHY:"A cup given for winning", LAUREL:"Leaves used as a mark of honor", WREATH:"A ring of leaves or flowers",
  GARLAND:"A string of flowers", BOUQUET:"A bunch of flowers", PETAL:"One leaf of a flower", POLLEN:"Yellow dust from flowers",
  NECTAR:"Sweet liquid in a flower", HONEYCOMB:"The wax store of a hive", BEEHIVE:"The home of a bee colony",
  WASP:"A stinging flying insect", ANTLER:"A deer's branched horn", FEATHER:"What covers a bird",
  TALON:"A bird of prey's claw", BEAK:"A bird's mouth", CLAW:"A sharp animal nail", PAW:"An animal's foot",
  HOOF:"A horse's foot", MANE:"Long hair on a horse's neck", TAIL:"The part behind an animal",
  WHISKER:"A long hair on a cat's face", MUZZLE:"An animal's nose and mouth", KENNEL:"A dog's house",
  QUILL:"A feather used as a pen", PENNIB:"The metal point of a pen", BLOTTER:"Paper that soaks extra ink",
  TYPECASE:"A tray of metal letters", GALLEYPROOF:"An early print checked for errors", LETTERPRESS:"Printing from raised type",
  OFFSET:"A modern printing method", LITHOGRAPHY:"Printing from a flat stone or plate", INTAGLIO:"Printing from a cut line",
  ETCHING:"A print made with acid", AQUATINT:"A tonal etching", MEZZOTINT:"A dark-to-light engraving",
  DRYPOINT:"A print scratched directly into a plate", BURIN:"An engraver's cutting tool", GOUGE:"A curved cutting tool",
  MALLET:"A wooden hammer", CHISEL:"A tool for cutting wood or stone", RASP:"A coarse file", FILE:"A tool that smooths metal",
  PLANE:"A tool that shaves wood", VISE:"A clamp that holds work", CLAMP:"It holds pieces together",
  DOWEL:"A round wooden pin", TENON:"A tongue cut to fit a mortise", MORTISE:"A hole cut to take a tenon",
  DOVETAIL:"A fan-shaped wood joint", RABBET:"A step cut on the edge of a board", DADO:"A groove across a board",
  GROOVE:"A long narrow cut", CHAMFER:"A sloped edge", BEVELED:"Cut at a slant", OGEE:"An S-shaped molding",
  FLUTE:"A groove, or a woodwind", REEDING:"Parallel rounded moldings", BEADING:"A small round molding",
  CORNICE:"The top molding of a wall", FRIEZE:"The band under a cornice", ARCHITRAVE:"The beam resting on columns",
  PEDIMENT:"The triangle over a doorway", LINTEL:"The beam over an opening", JAMB:"The side of a door frame",
  MULLION:"A bar dividing a window", TRANSOM:"A window above a door", QUOIN:"A corner stone",
  VOUSSOIR:"A wedge stone of an arch", SPRINGER:"The first stone of an arch", ABACUS:"The flat top of a column capital",
  ECHINUS:"The rounded part of a column capital", VOLUTE:"A spiral on a column", ACANTHUS:"A leaf carved on capitals",
  PALMETTE:"A fan-shaped leaf ornament", ANTHEMION:"A honeysuckle ornament", ROSETTE:"A carved rose",
  DENTIL:"A small tooth-like block in a cornice", COFFER:"A sunken panel in a ceiling", PENDENTIVE:"A curved triangle under a dome",
  SQUINCH:"An arch across a corner under a dome", OCULUS:"A round opening at a dome's crown",
  TRACERY:"Stone patterns in a window", TREFOIL:"A three-lobed shape", QUATREFOIL:"A four-lobed shape",
  CINQUEFOIL:"A five-lobed shape", ARIA:"A solo song in an opera", OVERTURE:"Music that opens a show",
  DIMINUENDO:"Music growing softer", STACCATO:"Notes played short and detached", LEGATO:"Notes played smoothly",
  TIMBRE:"The color of a sound", HARMONY:"Notes sounding together", DISSONANCE:"A clash of notes",
  CADENZA:"A solo flourish in a concerto", VIRTUOSO:"A player of great skill", MAESTRO:"A master musician",
  CONDUCTOR:"The person who leads an orchestra", QUARTET:"A group of four musicians", SONATA:"A piece for one or two players",
  FUGUE:"A piece where a theme chases itself", PRELUDE:"A short piece before a larger one", ETUDE:"A study piece for practice",
  NOCTURNE:"A night piece, often for piano", RHAPSODY:"A free, flowing piece", SYMPHONY:"A large work for orchestra",
  CONCERTO:"A work for soloist and orchestra", LIBRETTO:"The words of an opera", SCENARIO:"The outline of a play",
  FOOTLIGHTS:"Lights along the front of a stage", BACKDROP:"The cloth at the back of a stage", SCRIM:"A thin stage cloth",
  CYCLORAMA:"A curved cloth that makes a sky", CATWALK:"A narrow walk above a stage", RIGGING:"Ropes that fly scenery",
  BATTEN:"A bar that holds stage lights", FRESNEL:"A soft stage light", DIMMER:"A control that fades lights",
  CONSOLE:"The board that runs the lights", BLACKOUT:"A sudden dark on stage", AISLE:"The walk between seats",
  BALCONY:"An upper seating level", MEZZANINE:"A level between floor and balcony", TRAPDOOR:"A door in the floor",
  SERENADE:"Music played in the evening for someone", BALLAD:"A song that tells a story", ENCORE:"A piece played after applause",
  REHEARSAL:"A practice before the show", PROMPTER:"A person who feeds forgotten lines", GREENROOM:"Where actors wait",
  WARDROBE:"The clothes of a show", GREASEPAINT:"Stage makeup", SPOTLIGHT:"A hard beam on a performer",
  APPLAUSE:"The sound of clapping hands", CURTAINCALL:"The bow at the end of a show",
  SOLDIER:"A person in an army", TEACHER:"A person who gives lessons", STUDENT:"A person who learns",
  PENCIL:"A writing stick of graphite", ERASER:"It rubs out pencil marks", CRAYON:"A colored wax stick",
  MARKER:"A pen with a thick tip", NOTEBOOK:"A book of blank pages", BACKPACK:"A bag worn on the back",
  SANDWICH:"Food between two slices of bread", PANCAKE:"A flat cake cooked in a pan", COOKIE:"A small sweet biscuit",
  MUFFIN:"A small round cake", BANANA:"A long yellow fruit", CHERRY:"A small red stone fruit",
  PEPPER:"A hot or mild seasoning", ONION:"A layered bulb that makes you cry", GARLIC:"A strong-smelling bulb",
  BUTTER:"Fat churned from cream", CHEESE:"Food made from curdled milk", YOGURT:"A thick sour milk food",
  CEREAL:"A breakfast of grains", COFFEE:"A dark drink from roasted beans", SYRUP:"A thick sweet liquid",
  RAINBOW:"Colors arched after rain", SUNSET:"The sun going down", SUNRISE:"The sun coming up",
  EVENING:"The late part of the day", MORNING:"The early part of the day", MIDNIGHT:"Twelve at night",
  CALENDAR:"A chart of days", HOLIDAY:"A day of rest or celebration", BIRTHDAY:"The day you were born",
  PRESENT:"A gift", PACKAGE:"A wrapped parcel", LETTER:"A written message sent to someone",
  POSTCARD:"A card sent by mail", STAMP:"It pays for a letter", ENVELOPE:"The cover of a letter",
  ADDRESS:"Where a letter is sent", JOURNEY:"A trip from one place to another", VOYAGE:"A long journey, often by sea",
  TRAVEL:"To go from place to place", TICKET:"Proof you paid to enter or ride", STATION:"Where trains stop",
  AIRPORT:"Where planes take off", HARBOR:"A sheltered place for ships", LIGHTHOUSE:"A tower that warns ships",
  COMPASS:"It shows north", ANCHOR:"It holds a ship in place", SAILOR:"A person who works on a ship",
  VIOLIN:"A small bowed string instrument", TRUMPET:"A brass instrument you blow", SINGER:"A person who sings",
  DANCER:"A person who dances", WRITER:"A person who writes", ARTIST:"A person who makes art",
  FARMER:"A person who works the land", BAKER:"A person who makes bread", PILOT:"A person who flies a plane",
  CAPTAIN:"The person in command of a ship", COSTUME:"Clothes worn for a part", PURPOSE:"The reason for doing something",
  PASSION:"A strong feeling", PRESENTLY:"In a short while", PROTECT:"To keep from harm",
  EXACTLY:"With no mistake", BEDROOM:"The room where you sleep", COVERED:"Hidden or spread over",
  TRAFFIC:"Cars moving on a road", BENEFIT:"Something that helps", BROTHER:"A male sibling",
  CONTROL:"The power to direct", CURRENT:"A flow of water or electricity", KINGDOM:"The land a king rules",
  BALANCE:"An even weight on both sides", EXAMPLE:"A sample that shows the way",
  ARTICLE:"A piece of writing in a paper", CAPTURE:"To take hold of", CLIMATE:"The usual weather of a place",
  CLAIMED:"Said to be one's own", MARCHED:"Walked in step", DARLING:"A person dearly loved",
  LEATHER:"Hide made into a material", BATTERY:"A store of electrical power", COUNTRY:"A nation, or the land outside town",
  KITCHENETTE:"A very small kitchen", CRYSTAL:"A clear hard mineral", CLARITY:"The quality of being clear",
  PICTURE:"A painted or printed image", MACHINE:"A device that does work", CONCERT:"A musical performance",
  COURAGE:"Bravery", CROWDED:"Full of people", CUSTARD:"A sweet cooked milk dish",
  NEBULA:"A cloud of gas in space", QUASAR:"A very bright distant object", PULSAR:"A spinning star that flashes",
  GALAXY:"A huge system of stars", COMET:"A icy body with a tail", METEOR:"A streak of light in the sky",
  ASTEROID:"A small rocky body in space", ORBIT:"The path of a body around another", ECLIPSE:"One body hiding another",
  EQUINOX:"When day and night are equal", SOLSTICE:"The longest or shortest day", ZENITH:"The point straight overhead",
  NADIR:"The lowest point", HORIZON:"Where sky meets land", LATITUDE:"Distance north or south of the equator",
  LONGITUDE:"Distance east or west of a meridian", ALTITUDE:"Height above the sea", AZIMUTH:"A compass direction",
  MAGNITUDE:"The brightness of a star", SPECTRUM:"A band of colors", PRISM:"Glass that splits light",
  LENS:"Curved glass that bends light", FOCUS:"The sharp point of an image", APERTURE:"The opening in a lens",
  SHUTTER:"The door of a camera", NEGATIVE:"A reversed photographic image", EMULSION:"The light-sensitive coat on film",
  DAGUERREOTYPE:"An early photograph on metal", CALOTYPE:"An early paper photograph", CYANOTYPE:"A blue photographic print",
  PHOTOGRAVURE:"A print made from a photograph", HALFTONE:"A picture made of dots", COLLOTYPE:"A print from a gelatine plate",
  WOODCUT:"A print from a carved block", LINOCUT:"A print from carved linoleum", MONOTYPE:"A print that exists only once",
  ENGRAVING:"A print from a cut metal plate", WOODBLOCK:"A carved block for printing", TYPEFACE:"The design of a set of letters",
  SERIF:"A small stroke at the end of a letter", BASELINE:"The line letters sit on", LEADING:"Space between lines of type",
  KERNING:"Space between particular letters", LIGATURE:"Two letters joined as one", SMALLCAP:"A capital the size of a small letter",
  DROPCASE:"A large letter starting a paragraph", CATCHWORD:"A word repeated at the foot of a page",
  SIGNATURE:"A gathered section of a book", GATHERING:"Folded sheets ready to sew", ENDPAPER:"The sheet inside a book's cover",
  HEADBAND:"A decorative band at a book's head", BOOKMARK:"A strip that marks a page", MARBLING:"A swirling pattern on paper",
  DECKLE:"The rough edge of handmade paper", FOREEDGE:"The front edge of a book's pages",
  BUCKRAM:"A stiff cloth used on book covers", CALICO:"A plain cotton cloth", PARCHMENT:"Writing skin from sheep",
  PAPYRUS:"An early writing sheet from a reed", RAGPAPER:"Paper made from cloth fibers",
  CHINACLAY:"A fine white clay used in paper", FOUNTAINPEN:"A pen with its own ink store",
  DIPPEN:"A pen that must be dipped in ink", INKSTONE:"A stone for grinding ink", INKSTICK:"A solid cake of ink",
  BLOTTING:"Soaking up extra ink", SANDARAC:"A resin once dusted on ink", PUMICE:"A light stone used to smooth parchment",
  QUILLKNIFE:"A knife for cutting a pen", RULEDPAGE:"A page with guide lines", MARGIN:"The blank edge of a page",
  RECTO:"The front of a leaf", VERSO:"The back of a leaf", COLOPHONPAGE:"The page that tells how a book was made",
  IMPRINT:"The publisher's name in a book", ERRATA:"A list of printing mistakes", ADDENDA:"Material added at the end",
  PREFACE:"A note by the author at the front", FOREWORD:"A note by someone else at the front",
  INDEX:"A list of topics and pages", BIBLIOGRAPHY:"A list of books used", CITATION:"A note of a source",
  FOOTNOTING:"The practice of notes at the foot", CROSSREF:"A pointer to another place in a book",
  RUNNINGHEAD:"The title repeated at the top of pages", CATCHLINE:"A short line that identifies a story",
  SUBHEAD:"A smaller heading inside a story", KICKER:"A small line above a headline", DECK:"A summary under a headline",
  LEDE:"The opening of a news story", NUTGRAF:"The paragraph that states the point",
  GRAF:"A paragraph, in newsroom talk", SLUG:"A short name for a story", BUDGET:"The list of stories planned",
  RIM:"The desk that edits copy", SLOT:"The editor who runs the rim", COPYDESK:"Where stories are edited",
  REWRITE:"To write a story again", TRIM:"To cut a story shorter", CUTLINE:"The words under a photograph",
  CAPTION:"Words that explain a picture", MUGSHOT:"A head-and-shoulders photograph", WIREPHOTO:"A picture sent by wire",
  TELETYPE:"A machine that printed news by wire", CABLEGRAM:"A message sent by undersea cable",
  STRINGER:"A freelance reporter", BEAT:"A reporter's regular subject", SCOOP:"A story printed before rivals",
  EXCLUSIVE:"A story no other paper has", CORRECTION:"A note that fixes an error", RETRACTION:"A withdrawal of a false claim",
  OBITUARY:"A notice of a death", CLASSIFIED:"A small paid advertisement", DISPLAYAD:"A large illustrated advertisement",
  EAR:"A small box at the top corner of a page", FOLIO_LINE:"The page number and date line",
  JUMP:"A story continued on another page", JUMPLINE:"The line that says where a story continues",
  REFER:"A line pointing to a related story", TEASER:"A small notice of a story inside",
  BANNERHEAD:"A headline across the full page", SKYLINE:"A line above the paper's name",
  NAMEPLATE:"The paper's name as printed", EDITION:"One issue of the paper", EXTRA_EDITION:"A special issue for urgent news",
  BULLDOG:"An early edition", LOBSTER:"A very late edition", CITYDESK:"The desk that covers local news",
  WIREDESK:"The desk that handles agency copy", SPORTSBEAT:"The coverage of games",
  OBITDESK:"The desk that writes death notices", SOCIETY:"The pages about social events",
  AGONY:"The advice column", HOROSCOPE:"A column about the stars", CROSSWORD:"A puzzle of crossing words",
  CARTOON:"A drawn joke", COMICSTRIP:"A sequence of drawn panels", WEATHERBOX:"The small map of the forecast",
  TIDEBOX:"A table of high and low water", SHIPPING:"News of vessels in port", MARKETPAGE:"The page of prices",
  STOCKS:"Shares traded on an exchange", BONDS:"Loans traded as paper", FUTURES:"Contracts to buy later",
  COMMODITY:"A raw good that is traded", WHEAT:"A grain made into flour", BARLEY:"A grain used in bread and beer",
  OATS:"A grain fed to horses and people", RYE:"A dark grain for bread", MILLET:"A small grain",
  SORGHUM:"A tall grain plant", BUCKWHEAT:"A grain used in pancakes", QUINOA:"A small high-protein seed",
  LENTIL:"A small flat pulse", CHICKPEA:"A round beige pulse", SOYBEAN:"A bean used for oil and curd",
  ALMOND:"A nut from a flowering tree", WALNUT:"A wrinkled nut in a hard shell", HAZELNUT:"A small round nut",
  PISTACHIO:"A green nut in a split shell", CASHEW:"A curved nut", PECAN:"A long sweet nut",
  CHESTNUT:"A nut roasted in winter", COCONUT:"A large nut with white flesh", OLIVE:"A small fruit pressed for oil",
  FIG:"A soft fruit full of seeds", DATEFRUIT:"A sweet fruit of the palm", RAISIN:"A dried grape",
  PRUNE:"A dried plum", APRICOT:"A small orange stone fruit", PLUM:"A soft stone fruit",
  PEAR:"A fruit wider at the bottom", QUINCE:"A hard yellow fruit", POMEGRANATE:"A fruit full of red seeds",
  MANGO:"A tropical fruit with a flat stone", PAPAYA:"A soft tropical fruit", GUAVA:"A fragrant tropical fruit",
  LYCHEE:"A fruit with a rough pink skin", PASSIONFRUIT:"A fruit with a wrinkled skin and seeds",
  KIWI:"A brown fruit with green flesh", PINEAPPLE:"A tropical fruit with a crown of leaves",
  COCONUTMILK:"The liquid pressed from coconut", VANILLA:"A sweet pod used as flavor",
  CINNAMON:"A sweet bark spice", NUTMEG:"A warm spice from a seed", CLOVES:"Dried flower buds used as spice",
  GINGER:"A hot root used in cooking", TURMERIC:"A yellow root spice", SAFFRON:"A costly spice from crocus threads",
  CARDAMOM:"A fragrant seed pod", CUMIN:"A warm seed spice", CORIANDER:"A seed, or the leaf called cilantro",
  PAPRIKA:"A mild red pepper powder", MUSTARD:"A sharp yellow condiment", VINEGAR:"A sour liquid from wine",
  MOLASSES:"A dark syrup from sugar", TREACLE:"A thick dark syrup", HONEYJAR:"A pot of honey",
  BUTTERMILK:"The sour liquid left after churning", CREAM:"The rich top of milk", CURD:"Milk set firm",
  WHEY:"The watery part left from curd", RENNET:"What sets milk for cheese", RICOTTA:"A soft cheese from whey",
  MOZZARELLA:"A soft white cheese", PARMESAN:"A hard grating cheese", CHEDDAR:"A firm yellow cheese",
  BRIE:"A soft cheese with a white rind", GOUDA:"A mild Dutch cheese", FETA:"A salty white cheese",
  HALLOUMI:"A cheese that can be fried", PANEER:"A fresh cheese used in cooking",
  SOURDOUGH:"Bread raised with a living starter", BAGUETTE:"A long thin loaf", CIABATTA:"A flat Italian loaf",
  BRIOCHE:"A rich buttery bread", PRETZEL:"A twisted salted bread", BAGEL:"A boiled then baked ring of bread",
  CROISSANT:"A flaky crescent pastry", SCONE:"A small plain cake", BISCUIT:"A small baked bread or cookie",
  CRUMPET:"A griddle cake full of holes", WAFFLE:"A crisp cake from a patterned iron",
  GRIDDLE:"A flat pan for cakes", SKILLET:"A frying pan", LADLE:"A deep spoon for serving soup",
  WHISK:"A tool for beating eggs", SIEVE:"A mesh that strains", COLANDER:"A bowl with holes for draining",
  GRATER:"A tool that shreds", PEELER:"A tool that takes off skin", TONGS:"A tool for gripping food",
  SPATULA:"A flat tool for turning food", ROLLINGPIN:"A cylinder for flattening dough",
  CUTTINGBOARD:"The board you chop on", APRON:"A cloth worn while cooking", OVEN:"The box that bakes",
  STOVE:"The top where pots are heated", KETTLE:"A pot for boiling water", TEAPOT:"A pot for brewing tea",
  SAUCER:"The dish under a cup", TEASPOON:"A small spoon", TABLESPOON:"A large spoon",
  NAPKIN:"A cloth for the mouth", PLACEMAT:"A mat under a plate", CANDLESTICK:"A holder for a candle",
  CHANDELIER:"A hanging light with many arms", SCONCE:"A light fixed to a wall", LANTERNS:"More than one portable light",
  OIL:"A liquid used for light or cooking", WICK:"The string that burns in a candle",
  TALLOW:"Fat once used for candles", BEESWAX:"Wax from a hive", PARAFFIN:"A wax from petroleum",
  MATCHBOX:"A small box of matches", FLINT:"A stone that strikes a spark", TINDER:"Dry stuff that catches a spark",
  HEARTHSTONE:"The stone of a fireplace", ANDIRON:"A support for logs", FIREDOG:"Another name for an andiron",
  POKER:"A rod for stirring a fire", BELLOWS:"A tool that blows air on a fire", KINDLING:"Small wood for starting a fire",
  LOG:"A cut piece of a tree", CHARCOAL:"Burnt wood used as fuel", COAL:"A black mineral fuel",
  SOOT:"Black dust from smoke", CINDER:"A partly burnt piece", GRATE:"The bars a fire sits on",
  DAMPER:"A plate that controls a chimney", FLUE:"The passage for smoke", CHIMNEYPOT:"The pipe at a chimney's top"
};

let added = 0;
for (const [w, c] of Object.entries(EXTRA)) {
  if (!have.has(w) && /^[A-Z]{3,12}$/.test(w)) {
    CLUES[w] = c;
    have.add(w);
    added++;
  }
}
const words = Object.keys(CLUES);
console.log("clues", words.length, "added", added);
if (words.length < 1000) {
  console.log("SHORT", 1000 - words.length);
  process.exit(2);
}
const pool = words.slice(0, 1000);
const easy = pool.filter(w => w.length <= 4).slice(0, 250);
const medium = pool.filter(w => w.length >= 5 && w.length <= 7).slice(0, 350);
const hard = pool.filter(w => w.length >= 8).slice(0, 400);
// top up if a band is short
function top(arr, pred, n) {
  for (const w of pool) {
    if (arr.length >= n) break;
    if (!arr.includes(w) && pred(w)) arr.push(w);
  }
}
top(easy, w => w.length <= 5, 250);
top(medium, w => w.length >= 5 && w.length <= 8, 350);
top(hard, w => w.length >= 7, 400);
const used = new Set([...easy, ...medium, ...hard]);
const rest = pool.filter(w => !used.has(w));
console.log({ easy: easy.length, medium: medium.length, hard: hard.length, rest: rest.length, unique: used.size });
const clueObj = {};
for (const w of [...easy, ...medium, ...hard]) clueObj[w] = CLUES[w];
fs.writeFileSync("_bank.json", JSON.stringify({ easy, medium, hard, clues: clueObj }));
console.log("bank words", Object.keys(clueObj).length);
